### ISSUE TITLE
Move to openHAB Github org

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/org.openhab.ui.habot#25]
Now that https://github.com/eclipse/smarthome/pull/6288 is available, I'd suggest to move this awesome project to openHAB.

As the repo structure and history is pretty clean, I think the best option is to simply transfer the repo to https://github.com/openhab (instead of creating a new repo with a new initial commit).

Once transferred, I'd include it in the official openHAB build, so that it'd be directly built and available in the latest snapshots.

@ghys Does this sound like a plan?

**Comment by ghys** [comment]
> @ghys Does this sound like a plan?

Sure! - note that #24 is still not merged (I also have some plans for it first) and the build currently fails, see:
https://travis-ci.org/ghys/habot/builds/440753226
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.ui.habot 2.4.0.qualifier
[ERROR]   Missing requirement: org.openhab.ui.habot 2.4.0.qualifier requires 'java.package; org.eclipse.smarthome.core.semantics 0.0.0' but it could not be found
```
I'm not familiar with Tycho/p2 but I suppose there's something to be done in openhab-core or openhab-distro first.

**Comment by kaikreuzer** [comment]
> I suppose there's something to be done in openhab-core 

You are right! https://github.com/openhab/openhab-core/pull/415 should solve this.

**Comment by kaikreuzer** [comment]
Looks as if we can close this :-)
